src/AppBundle/Entity/Usuario.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use FOS\UserBundle\Model\User as BaseUser;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class Usuario
 *
 * @author Guillermo Quinteros <gu.quinteros@gmail.com> 2015
 *
 * @package AppBundle\Entity
 *
 * @ORM\Table(name="Usuario")
 *
 * @ORM\Entity(repositoryClass="AppBundle\Repository\UsuarioRepository")
 */
class Usuario extends BaseUser
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    protected $id;

    /**
     * @var string
     * @Assert\NotBlank(message="not_blank")
     * @ORM\Column(name="nombres", type="string", length=255, nullable=true)
     */
    private $nombres;

    /**
     * @var string
     * @Assert\NotBlank(message="not_blank")
     * @ORM\Column(name="apellidos", type="string", length=255, nullable=true)
     */
    private $apellidos;

    /**
     * @var string
     *
     * @ORM\Column(name="avatar", type="string", length=255, nullable=true)
     */
    private $avatar;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getNombres()
    {
        return $this->nombres;
    }

    /**
     * @param $nombres
     * @return $this
     */
    public function setNombres($nombres)
    {
        $this->nombres = $nombres;

        return $this;
    }

    /**
     * @return string
     */
    public function getApellidos()
    {
        return $this->apellidos;
    }

    /**
     * @param $apellidos
     * @return $this
     */
    public function setApellidos($apellidos)
    {
        $this->apellidos = $apellidos;

        return $this;
    }

    /**
     * @return string
     */
    public function getFullName()
    {
        return $this->getNombres().' '.$this->getApellidos();
    }

    /**
     * @return string
     */
    public function getAvatar()
    {
        return $this->avatar;
    }

    /**
     * @param $avatar
     * @return $this
     */
    public function setAvatar($avatar)
    {
        $this->avatar = $avatar;

        return $this;
    }
}

src/AppBundle/Resources/views/Charts/AcumuladoIndex.html.twig
{% extends '::base.html.twig' %}
{% block stylesheet %}
    <link href="{{ asset('bundles/app/plugins/morris/morris.css') }}" rel="stylesheet">
    <link href="{{ asset('bundles/app/plugins/DataTables/media/css/jquery.dataTables.min.css') }}" rel="stylesheet">
{% endblock %}
{% block header %}
{% endblock %}
{% block body %}
    <div class="panel panel-inverse" data-sortable-id="ui-general-2">
        <div class="panel-heading">
            <h4 class="panel-title">Acumulado</h4>
        </div>
        <div id="results" class="panel-body">
            <center><i style='font-size: 300px;opacity: 0.3' class='fa fa-signal'></i></center>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    <script src="{{ asset('bundles/app/plugins/morris/raphael.min.js') }}"></script>
    <script src="{{ asset('bundles/app/charts/highcharts.js') }}"></script>
    <script src="{{ asset('bundles/app/charts/exporting.js') }}"></script>
    <script src="{{ asset('bundles/app/plugins/morris/morris.js') }}"></script>
    <script src="{{ asset('bundles/app/plugins/bootbox-4.3.0/bootbox.js') }}"></script>
    <script src="{{ asset('bundles/app/plugins/datatable/datatables.min.js') }}"></script>
    <script src="{{ asset('bundles/app/plugins/bootstrap-select/bootstrap-select.min.js') }}"></script>
    <script src="{{ asset('bundles/app/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js') }}"></script>
    <script src="{{ asset('bundles/app/plugins/masked-input/masked-input.min.js') }}"></script>
    <script src="{{ asset('bundles/app/js/fncrud.js') }}"></script>
    <script>
        $(document).on('ready', function() {
            console.log('ijadjaskdas');
            $('#obras').chosen();
            $('#menu-li-acumulado').addClass('active').closest('.has-sub').addClass('active');
            graficaObra();
        });

        /**
         *
         * @param $obras
         */
        function graficaObra()
        {
            $('#results').html("<center><i style='font-size: 100px;' class='fa fa-cog fa-spin'></i><br>Generando...</center>");
            var path = "{{ path('acumulado_result') }}";
            $.ajax({
                type: 'POST',
                async: true,
                url: path,
                success: function(results) {
                    $('#results').html(results);
                },
                error: function(e){
                    console.log(e);
                }
            });
        }
    </script>
{% endblock %}

src/AppBundle/Resources/views/Charts/AcumuladoResult.html.twig
{% block body %}
    <div class="panel-body">
        {#<div id="myfirstchart" style="height: 250px;"></div>#}
        <div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
        <br>
        <br>
        <br>
        <hr>
        <table id="table-entities" class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>Fecha</th>
                <th>Esperado</th>
                <th>Real</th>
                <th>Porcentaje</th>
            </tr>
            </thead>
            <tbody>
            {% for key, value in acumulado %}
                {% if value['esperado'] != 0 %}
                    <tr {% if value['porcentaje'] < 100  and value['esperado'] != 0 %} class="danger" {% else %} class="success" {% endif %}>
                        <td>{{ key }}</td>
                        <td>{{ value['esperado'] }}</td>
                        <td>{{ value['real'] }}</td>
                        <td>{{ value['porcentaje'] }} %</td>
                    </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>
    </div>
    {#<script type="text/javascript">#}
        {#var chart_data = [];#}
        {#{% for key, value in acumulado %}#}
        {#chart_data.push({ y: '{{ key }}', a: '{{ value['esperado'] }}', b: '{{ value['real'] }}' });#}
        {#{% endfor %}#}

        {#new Morris.Line({#}
            {#element: 'myfirstchart',#}
            {#data: chart_data,#}
            {#xkey: 'y',#}
            {#ykeys: ['a', 'b'],#}
            {#labels: ['Avance Ideal', 'Avance Real']#}
        {#});#}
    {#</script>#}
    <script type="text/javascript">
    $(function () {
        var categories = [];
        {% for key, value in acumulado %}
        categories.push('{{ key }}');
        {% endfor %}

        var ideal = [];
        {% for key, value in acumulado %}
        ideal.push(parseInt('{{ value['esperado'] }}'));
        {% endfor %}

        var real = [];
        {% for key, value in acumulado %}
        real.push(parseInt('{{ value['real'] }}'));
        {% endfor %}

        $('#container').highcharts({
            title: {
            text: '',
            x: -20 //center
            },
            xAxis: {
                categories: categories
            },
            yAxis: {
                title: {
                text: 'Nº Tareas'
            },
            plotLines: [{
                value: 0,
                width: 1,
                color: '#808080'
            }]
            },
            tooltip: {
                valueSuffix: 'Tareas'

            },
            legend: {
                layout: 'vertical',
                align: 'right',
                verticalAlign: 'middle',
                borderWidth: 0
            },
            series: [{
                name: 'Ideal',
                data: ideal
            }, {
                name: 'Real',
                data: real
            }]
        });
    });
    </script>
{% endblock %}

src/AppBundle/Resources/views/Charts/RendimientoCumplimientoIndex.html.twig
{% extends '::base.html.twig' %}
{% block stylesheet %}
    <link href="{{ asset('bundles/app/plugins/morris/morris.css') }}" rel="stylesheet">
    <link href="{{ asset('bundles/app/plugins/DataTables/media/css/jquery.dataTables.min.css') }}" rel="stylesheet">
{% endblock %}
{% block header %}
{% endblock %}
{% block body %}
    <div class="panel panel-info" data-sortable-id="ui-buttons-1" -="">
        <div class="panel-body">
            <div class="col-md-6">
                <select id="obra" class="form-control">
                    <option selected disabled >Seleccione una Obra</option>
                    {% for obra in obras %}
                        <option value="{{ obra.id }}">{{ obra.nombre }}</option>
                    {% endfor %}
                </select>
            </div>
            {#<div class="col-md-2">#}
                {#<a onclick="graficaObra()" class="btn btn-block btn-success"><i class="fa fa-signal"></i> 12 Meses</a>#}
            {#</div>#}
            <div class="col-md-3">
                <a onclick="graficaObraCompleto()" class="btn btn-block btn-info"><i class="fa fa-signal"></i> Avance</a>
            </div>
            <div class="col-md-3">
                <a onclick="graficaObraCompletoRendimiento()" class="btn btn-block btn-success"><i class="fa fa-signal"></i> Rendimiento</a>
            </div>
        </div>
    </div>
    <div class="panel panel-inverse" data-sortable-id="ui-general-2">
        <div class="panel-heading">
            <h4 class="panel-title">Obras</h4>
        </div>
        <div id="results" class="panel-body">
            <center><i style='font-size: 300px;opacity: 0.3' class='fa fa-signal'></i></center>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    <script src="{{ asset('bundles/app/plugins/morris/raphael.min.js') }}"></script>
    <script src="{{ asset('bundles/app/plugins/morris/morris.js') }}"></script>
    <script src="{{ asset('bundles/app/charts/highcharts.js') }}"></script>
    <script src="{{ asset('bundles/app/charts/exporting.js') }}"></script>
    <script src="{{ asset('bundles/app/plugins/bootbox-4.3.0/bootbox.js') }}"></script>
    <script src="{{ asset('bundles/app/plugins/datatable/datatables.min.js') }}"></script>
    <script src="{{ asset('bundles/app/plugins/bootstrap-select/bootstrap-select.min.js') }}"></script>
    <script src="{{ asset('bundles/app/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js') }}"></script>
    <script src="{{ asset('bundles/app/plugins/masked-input/masked-input.min.js') }}"></script>
    <script src="{{ asset('bundles/app/js/fncrud.js') }}"></script>
    <script>
        $(document).on('ready', function() {
            $('#menu-li-rendimiento-cumplimientos').addClass('active').closest('.has-sub').addClass('active');
            console.log('ijadjaskdas');
            $('#obras').chosen();
        });

        /**
         *
         * @param $obras
         */
        function graficaObra()
        {
            var idObra = $('#obra').val();
            if (!idObra) {
                $('#results').html("<center><br>Debe seleccionar una obra...</center>");
                return false;
            }

            $('#results').html("<center><i style='font-size: 100px;' class='fa fa-cog fa-spin'></i><br>Generando...</center>");

            var path = "{{ path('rendimiento_cumplimiento_result') }}";
            $.ajax({
                type: 'POST',
                async: true,
                data: {
                    'obra': idObra
                },
                url: path,
                success: function(results) {
                    $('#results').html(results);
                },
                error: function(e){
                    console.log(e);
                }
            });
        }

        /**
         *
         * @param $obras
         */
        function graficaObraCompleto()
        {
            var idObra = $('#obra').val();
            if (!idObra) {
                $('#results').html("<center><br>Debe seleccionar una obra...</center>");
                return false;
            }

            $('#results').html("<center><i style='font-size: 100px;' class='fa fa-cog fa-spin'></i><br>Generando...</center>");
            var path = "{{ path('rendimiento_cumplimiento_completo_result') }}";
            $.ajax({
                type: 'POST',
                async: true,
                data: {
                    'obra': idObra
                },
                url: path,
                success: function(results) {
                    $('#results').html(results);
                },
                error: function(e){
                    console.log(e);
                }
            });
        }

        /**
         *
         * @param $obras
         */
        function graficaObraCompletoRendimiento()
        {
            var idObra = $('#obra').val();
            if (!idObra) {
                $('#results').html("<center><br>Debe seleccionar una obra...</center>");
                return false;
            }

            $('#results').html("<center><i style='font-size: 100px;' class='fa fa-cog fa-spin'></i><br>Generando...</center>");
            var path = "{{ path('rendimiento_cumplimiento_completo_result_rendimiento') }}";
            $.ajax({
                type: 'POST',
                async: true,
                data: {
                    'obra': idObra
                },
                url: path,
                success: function(results) {
                    $('#results').html(results);
                },
                error: function(e){
                    console.log(e);
                }
            });
        }
    </script>
{% endblock %}

src/AppBundle/Resources/views/Charts/RendimientoCumplimientoResult.html.twig
{% block body %}
    {% if entity %}
    <h1 class="page-header">
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i class="fa fa-building"></i> {{ entity.nombre }} <small>{{ entity.direccion }}</small>
    </h1>
    <h2>
        &nbsp;&nbsp;&nbsp;&nbsp;<i class="fa fa-user"></i> <small> Responsable : {{ entity.responsable.fullName }}  - <i class="fa fa-envelope"></i> <a href="mailto:{{ entity.responsable.email }}?Subject={{ entity.nombre }}" target="_top">Enviar email</a></small></h2>
    <div class="panel-body">
        {#<div id="myfirstchart" style="height: 250px;"></div>#}
        <br>
        <br>
        <br>
        <div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
        <hr>
        <table id="table-entities" class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>Fecha</th>
                <th>Esperado</th>
                <th>Real</th>
                <th>Porcentaje</th>
            </tr>
            </thead>
            <tbody>
            {% for key, value in obraResult %}
                {% if value['esperado'] != 0 %}
                    <tr {% if value['porcentaje'] < 100  and value['esperado'] != 0 %} class="danger" {% else %} class="success" {% endif %}>
                        <td>{{ key }}</td>
                        <td>{{ value['esperado'] }}</td>
                        <td>{{ value['real'] }}</td>
                        <td>{{ value['porcentaje']|round }} %</td>
                    </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>
    </div>
    {#<script type="text/javascript">#}
        {#var chart_data = [];#}
        {#{% for key, value in obraResult %}#}
        {#chart_data.push({ y: '{{ key }}', a: '{{ value['esperado'] }}', b: '{{ value['real'] }}' });#}
        {#{% endfor %}#}

{#//        console.log(chart_data);#}

        {#new Morris.Line({#}
            {#element: 'myfirstchart',#}
            {#data: chart_data,#}
            {#xkey: 'y',#}
            {#ykeys: ['a', 'b'],#}
            {#labels: ['Rendimiento Ideal', 'Rendimiento Real']#}
        {#});#}
    {#</script>#}
        <script type="text/javascript">
            $(function () {

                var categories = [];
                {% for key, value in obraResult %}
                categories.push('{{ key }}');
                {% endfor %}

                var ideal = [];
                {% for key, value in obraResult %}
                ideal.push(parseInt('{{ value['esperado'] }}'));
                {% endfor %}

                console.log(ideal);

                var real = [];
                {% for key, value in obraResult %}
                real.push(parseInt('{{ value['real'] }}'));
                {% endfor %}

                console.log(real);


                $('#container').highcharts({
                    title: {
                        text: '',
                        x: -20 //center
                    },
                    xAxis: {
                        categories: categories
                    },
                    yAxis: {
                        title: {
                            text: 'Nº Tareas'
                        },
                        plotLines: [{
                            value: 0,
                            width: 1,
                            color: '#808080'
                        }]
                    },
                    tooltip: {
                        valueSuffix: ' Tareas'
                    },
                    legend: {
                        layout: 'vertical',
                        align: 'right',
                        verticalAlign: 'middle',
                        borderWidth: 0
                    },
                    series: [{
                        name: 'Ideal',
                        data: ideal
                    }, {
                        name: 'Real',
                        data: real
                    }]
                });
            });
        </script>
        {% else %}
            Debe Seleccionar al menos Una Obra
        {% endif %}

{% endblock %}

src/AppBundle/Resources/views/Charts/RendimientoCumplimientoResultBody.html.twig
{% block body %}
    {% if entity %}
    <div class="panel panel-info" data-sortable-id="ui-buttons-1" -="">
        <div class="panel-body">
            <a onclick="verDetallesObra({{ entity.id }});" class="btn btn-block btn-success"><i class="fa fa-arrow-circle-left" aria-hidden="true"></i> Volver a la obra</a>
            <hr>
            <div class="col-md-12">
                <h1 class="page-header">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i class="fa fa-building"></i> {{ entity.nombre }} <small>{{ entity.direccion }}</small>
                </h1>
                <h2>
                    &nbsp;&nbsp;&nbsp;&nbsp;<i class="fa fa-user"></i> <small> Responsable : {{ entity.responsable.fullName }}  - <i class="fa fa-envelope"></i> <a href="mailto:{{ entity.responsable.email }}?Subject={{ entity.nombre }}" target="_top">Enviar email</a></small></h2>
                <div class="panel-body">
                    <div id="myfirstchart" style="height: 250px;"></div>
                    <br>
                    <br>
                    <br>
                    <hr>
                    <table id="table-entities" class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>Fecha</th>
                            <th>Esperado</th>
                            <th>Real</th>
                            <th>Porcentaje</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for key, value in obraResult %}
                            {% if value['esperado'] != 0 %}
                                <tr {% if value['porcentaje'] < 100  and value['esperado'] != 0 %} class="danger" {% else %} class="success" {% endif %}>
                                    <td>{{ key }}</td>
                                    <td>{{ value['esperado'] }}</td>
                                    <td>{{ value['real'] }}</td>
                                    <td>{{ value['porcentaje']|round }} %</td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        var chart_data = [];
        {% for key, value in obraResult %}
        chart_data.push({ y: '{{ key }}', a: '{{ value['esperado'] }}', b: '{{ value['real'] }}' });
        {% endfor %}

        new Morris.Line({
            element: 'myfirstchart',
            data: chart_data,
            xkey: 'y',
            ykeys: ['a', 'b'],
            labels: ['Avance Ideal', 'Avance Real']
        });
    </script>
        {% else %}
            Debe Seleccionar al menos Una Obra
        {% endif %}
{% endblock %}

src/AppBundle/Resources/views/Charts/index.html.twig
{% extends '::base.html.twig' %}
{% block stylesheet %}
    <link href="{{ asset('bundles/app/plugins/DataTables/media/css/jquery.dataTables.min.css') }}" rel="stylesheet">
{% endblock %}
{% block header %}
{% endblock %}
{% block body %}
    <div class="panel panel-info" data-sortable-id="ui-buttons-1" -="">
        <div class="panel-body">
            <div class="col-md-9">
                <select id="obras" multiple="" class="form-control" data-placeholder=" Seleccione las obras a comparar">
                    {% for obra in obras %}
                        <option value="{{ obra.id }}">{{ obra.nombre }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-md-3">
                <a onclick="comparaObras()" class="btn btn-success"><i class="fa fa-signal"></i> Comparar</a>
            </div>
        </div>
    </div>
    <div class="panel panel-inverse" data-sortable-id="ui-general-2">
        <div class="panel-heading">
            <h4 class="panel-title">Obras</h4>
        </div>
        <div id="results" class="panel-body">
            <center><i style='font-size: 300px;opacity: 0.3' class='fa fa-signal'></i></center>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    <script src="{{ asset('bundles/app/plugins/bootbox-4.3.0/bootbox.js') }}"></script>
    <script src="{{ asset('bundles/app/plugins/datatable/datatables.min.js') }}"></script>
    <script src="{{ asset('bundles/app/plugins/bootstrap-select/bootstrap-select.min.js') }}"></script>
    <script src="{{ asset('bundles/app/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js') }}"></script>
    <script src="{{ asset('bundles/app/plugins/masked-input/masked-input.min.js') }}"></script>
    <script src="{{ asset('bundles/app/js/fncrud.js') }}"></script>
    <script>
        $(document).on('ready', function() {
            $('#menu-li-comparacion-obras').addClass('active').closest('.has-sub').addClass('active');
            console.log('ijadjaskdas');
            $('#obras').chosen();
        });

        /**
         *
         * @param $obras
         */
        function comparaObras()
        {
            //cambio el contenido del div 'results', por el de cargando.
            $('#results').html("<center><i style='font-size: 100px;' class='fa fa-cog fa-spin'></i><br>Generando...</center>");

            //obras , contiene el total de las obras seleccionadas
            var obras = [];
            $('#obras :selected').each(function(i, selected){
                obras[i] = $(selected).val();
            });
            var path = "{{ path('reportes_result_comparacion') }}";
            $.ajax({
                type: 'POST',
                async: true,
                data: {
                    'obras': obras
                },
                url: path,
                success: function(results) {
                    $('#results').html(results);
                },
                error: function(e){
                    console.log(e);
                }
            });
        }
    </script>
{% endblock %}